### ISSUE TITLE
Remove Base64.java 

### ISSUE THREAD

**Issue by kdbeall** [kdbeall/receipt_checker#3]
-Probably find a Base64 library from Maven Central

**Comment by hans123456** [comment]
What is the minimum Java version?

**Comment by hans123456** [comment]
Created a PR to use Jackson mapper for Base64, but didn't add a new library.

**Comment by kdbeall** [comment]
@hans123456 That's probably the better approach!

**Comment by kdbeall** [comment]
Hmm... bit confused about how ```convertValue``` works. Ended up using the Base64 included in Java utils.
